# Generated by Django 6.0.2 on 2026-02-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availabel',
            new_name='is_available',
        ),
    ]
