# Generated by Django 6.0.2 on 2026-03-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_is_active_cartitem_is_activee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_activee',
            new_name='is_active',
        ),
    ]
