# Generated by Django 6.0.2 on 2026-02-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_category_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
    ]
