# Generated by Django 6.0.2 on 2026-02-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_category_name_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
